# [general]
# import = ["~/.config/alacritty/alacritty-theme/themes/material_theme_mod.toml"]

# shell.program = "fish"
# shell = "/run/current-system/sw/bin/fish"
# shell.program = "/run/current-system/sw/bin/fish"

[font]
size = 14.0

[font.normal]
family = "ZedMono Nerd Font"
# family = "GeistMono Nerd Font"
# style = "SemiBold"
# family = "Monocraft Nerd Font"

[window]
decorations = "none"
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
