import = ["./alacritty-theme/themes/material_theme_mod.toml"]

shell = "/opt/homebrew/bin/fish"

[font]
size = 15.0

[font.normal]
family = "GeistMono Nerd Font Mono"

[window]
decorations = "none"
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
