# [general]
# import = ["~/.config/alacritty/alacritty-theme/themes/material_theme_mod.toml"]

# shell.program = "fish"
# shell = "/run/current-system/sw/bin/fish"
# shell.program = "/run/current-system/sw/bin/fish"

[font]
size = 12.0

[font.normal]
# family = "ZedMono Nerd Font"
# family = "Monocraft Nerd Font"
# family = "GeistMono Nerd Font"
style = "Medium"

[window]
decorations = "none"
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
