import = ["./alacritty-theme/themes/material_theme_mod.toml"]

shell = "fish"

[font]
size = 12.0

[font.normal]
family = "GeistMono Nerd Font"
style = "semibold"

[window]
decorations = "none"
dynamic_title = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
