import = ["./alacritty-theme/themes/material_theme_mod.toml"]

shell = "/opt/homebrew/bin/fish"

[cursor]
vi_mode_style = "Block"

[cursor.style]
shape = "Beam"

[font]
size = 15.0

[font.normal]
family = "GeistMono Nerd Font Mono"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command|Control"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.7
option_as_alt = "Both"
blur = true
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
